// Honeymoon Mediterranean Cruise itinerary (updated with MSC schedule)
// Source: MSC cruise app screenshots (capture 2026-04-29) + Gemini planning notes
// Cruise: 5/11 (Mon) board Barcelona → 5/18 (Mon) disembark Barcelona — 7 nights
// Itinerary order: Barcelona → At Sea → Tunisia → Palermo → Rome → Savona → Marseille → Barcelona
// Coordinates are approximate; refine after first arrival if needed.

const TRIP = {
  id: 'honeymoon-2026-med',
  title: '허니문 지중해 크루즈',
  subtitle: 'MSC 크루즈 7박 · 바르셀로나 출발',
  dateRange: '2026.05.10 ~ 2026.05.19',
  travelers: ['남편', '와이프'],
  currency: 'EUR',
  emergency: {
    korea_embassy_spain: '+34-913-532-217',
    korea_embassy_italy: '+39-06-802-461',
    korea_embassy_france: '+33-1-47-53-01-01',
    korea_embassy_tunisia: '+216-71-861-845',
    eu_emergency: '112',
    travel_insurance: '(가입한 보험사 24시 핫라인 입력)',
  },
  days: [
    {
      date: '2026-05-10',
      weekday: '일',
      title: '바르셀로나 도착',
      subtitle: '여유로운 첫날밤',
      city: 'Barcelona',
      cityCenter: { lat: 41.3851, lng: 2.1734 },
      events: [
        {
          time: '20:30',
          title: '숙소 체크인',
          desc: 'SM Hotel Teatre Auditori 체크인',
          location: { name: 'SM Hotel Teatre Auditori', lat: 41.4012, lng: 2.1909 },
          radius: 200,
          tag: 'hotel',
        },
        {
          time: '21:00',
          title: '저녁 식사',
          desc: '호텔 근처 분위기 좋은 타파스 바 (추천: Can Recasens, Poblenou)',
          location: { name: 'Can Recasens', lat: 41.4014, lng: 2.1960 },
          radius: 150,
          tag: 'food',
        },
        {
          time: '22:30',
          title: '숙소 복귀 및 휴식',
          desc: '시차 적응. 다음 날 일찍 일어날 것.',
          tag: 'rest',
        },
      ],
    },
    {
      date: '2026-05-11',
      weekday: '월',
      title: '크루즈 승선 (Day 1)',
      subtitle: '바르셀로나 → MSC 승선',
      city: 'Barcelona',
      cityCenter: { lat: 41.3851, lng: 2.1734 },
      tips: '🛳️ 승선 일정: 09:00 입항 · 14:00 보딩 시작 · 17:30 전원 승선 · 18:00 출항. 14:00~17:00 사이 체크인 권장.',
      events: [
        {
          time: '09:30',
          title: '체크아웃 & 짐 보관',
          desc: '호텔 프론트에 짐 보관',
          location: { name: 'SM Hotel Teatre Auditori', lat: 41.4012, lng: 2.1909 },
          radius: 150,
          tag: 'hotel',
        },
        {
          time: '10:00',
          title: '고딕 지구 도보 산책',
          desc: '바르셀로나 대성당 주변 중세 골목과 상점 구경',
          location: { name: 'Catedral de Barcelona', lat: 41.3839, lng: 2.1761 },
          radius: 250,
          tag: 'walk',
        },
        {
          time: '12:00',
          title: '점심 식사',
          desc: '고딕 지구 내 식당에서 가벼운 점심',
          location: { name: 'Gothic Quarter', lat: 41.3825, lng: 2.1769 },
          radius: 250,
          tag: 'food',
        },
        {
          time: '13:00',
          title: '호텔 복귀 & 짐 픽업',
          location: { name: 'SM Hotel Teatre Auditori', lat: 41.4012, lng: 2.1909 },
          radius: 150,
          tag: 'hotel',
        },
        {
          time: '13:30',
          title: '크루즈 터미널 이동 (택시)',
          desc: '바르셀로나 크루즈 터미널까지 약 25분',
          location: { name: 'Barcelona Cruise Terminal', lat: 41.3536, lng: 2.1714 },
          radius: 300,
          tag: 'transport',
        },
        {
          time: '14:00',
          title: '🛳️ 크루즈 승선 시작 (보딩)',
          desc: '여권/승선권 준비. 객실 캐리어 보관 후 선내 산책.',
          location: { name: 'Barcelona Cruise Terminal', lat: 41.3536, lng: 2.1714 },
          radius: 300,
          tag: 'cruise',
        },
        {
          time: '17:30',
          title: '⚠️ 전원 승선 마감',
          desc: '늦으면 항구 직원이 호명. 승선 카드 준비.',
          tag: 'cruise',
        },
        {
          time: '18:00',
          title: '🚢 출항 — 바르셀로나 → 튀니지',
          desc: '갑판에서 출항 풍경 감상',
          tag: 'cruise',
        },
      ],
    },
    {
      date: '2026-05-12',
      weekday: '화',
      title: '해상일 (Day 2)',
      subtitle: '선상 휴식 — 튀니지 향발',
      city: 'At Sea',
      cityCenter: null,
      tips: '하루 종일 바다. 시차 적응에 가장 좋은 날. 풀 데크/스파/쇼 즐기기.',
      events: [
        { time: '09:00', title: '여유 아침', desc: '뷔페 또는 룸서비스', tag: 'food' },
        { time: '11:00', title: '선상 시설 탐색', desc: '풀 데크, 스파, 피트니스, 라이브러리', tag: 'rest' },
        { time: '13:00', title: '점심', desc: '메인 식당 또는 캐주얼 뷔페', tag: 'food' },
        { time: '15:00', title: '선상 액티비티', desc: 'MSC Today 일정 확인 (요가, 칵테일 클래스, 쇼핑 이벤트)', tag: 'rest' },
        { time: '19:30', title: '저녁 식사', desc: '메인 다이닝 (드레스 코드 캐주얼)', tag: 'food' },
        { time: '21:30', title: '선상 쇼 / 갑판 산책', tag: 'rest' },
      ],
    },
    {
      date: '2026-05-13',
      weekday: '수',
      title: '🇹🇳 튀니지 라 굴레트 (Day 3)',
      subtitle: '북아프리카의 산토리니 — 시디 부 사이드',
      city: 'La Goulette',
      cityCenter: { lat: 36.8189, lng: 10.3056 },
      tips: '🛳️ 항구 일정: 08:00 입항 · 17:30 전원 승선 · 18:00 출항. 항구→시디부사이드 차로 20분.',
      events: [
        {
          time: '08:00',
          title: '🛳️ 라 굴레트 입항',
          desc: '튀니스의 외항. 하선은 보통 08:30~09:00 시작.',
          location: { name: 'La Goulette Port, Tunis', lat: 36.8189, lng: 10.3056 },
          radius: 300,
          tag: 'cruise',
        },
        {
          time: '09:00',
          title: '하선 + 시디 부 사이드 이동',
          desc: '택시 또는 선상 투어. 차로 약 20분.',
          location: { name: 'Sidi Bou Said', lat: 36.8702, lng: 10.3417 },
          radius: 400,
          tag: 'transport',
        },
        {
          time: '09:30',
          title: '시디 부 사이드 마을 산책',
          desc: '북아프리카의 산토리니. 파란색·흰색 골목, 지중해 전망.',
          location: { name: 'Sidi Bou Said', lat: 36.8702, lng: 10.3417 },
          radius: 400,
          tag: 'walk',
        },
        {
          time: '11:00',
          title: '카페 데 나테스 (Café des Nattes)',
          desc: '아랍식 민트티 + 마카롱. 마을 중심.',
          location: { name: 'Café des Nattes', lat: 36.8704, lng: 10.3437 },
          radius: 80,
          tag: 'food',
        },
        {
          time: '12:30',
          title: '점심 식사',
          desc: '쿠스쿠스, 브릭(Brick) 등 튀니지 전통',
          location: { name: 'Sidi Bou Said', lat: 36.8702, lng: 10.3417 },
          radius: 300,
          tag: 'food',
        },
        {
          time: '14:00',
          title: 'White & Blue Cages (수공예)',
          desc: '시디 부 사이드 명물 — 새장 모양 수공예 등.',
          location: { name: 'Sidi Bou Said Souk', lat: 36.8702, lng: 10.3415 },
          radius: 200,
          tag: 'shop',
        },
        {
          time: '14:45',
          title: 'Rock the Kasbah',
          desc: '튀니지 전통 + 현대 디자인 편집숍. 세라믹/카페트.',
          location: { name: 'Rock the Kasbah Sidi Bou Said', lat: 36.8703, lng: 10.3420 },
          radius: 100,
          tag: 'shop',
        },
        {
          time: '15:30',
          title: '선택: 카르타고 유적 (시간 여유 시)',
          desc: '시디 부 사이드 ↔ 카르타고 차로 10분',
          location: { name: 'Carthage Archaeological Site', lat: 36.8528, lng: 10.3239 },
          radius: 500,
          tag: 'walk',
        },
        {
          time: '16:30',
          title: '항구로 복귀 시작',
          desc: '택시 호출. 늦어도 17:00 도착',
          tag: 'transport',
        },
        {
          time: '17:30',
          title: '⚠️ 전원 승선 마감',
          desc: '늦으면 다음 항구(팔레르모)에서 자비로 합류',
          tag: 'cruise',
        },
        {
          time: '18:00',
          title: '🚢 출항 — 튀니지 → 팔레르모',
          tag: 'cruise',
        },
      ],
    },
    {
      date: '2026-05-14',
      weekday: '목',
      title: '🇮🇹 팔레르모 (Day 4)',
      subtitle: '시칠리아의 심장',
      city: 'Palermo',
      cityCenter: { lat: 38.1157, lng: 13.3613 },
      tips: '🛳️ 08:00 입항 · 16:00 전원 승선 · 16:30 출항. 일정 짧음 — 점심 먼저.',
      events: [
        {
          time: '08:00',
          title: '🛳️ 팔레르모 입항',
          location: { name: 'Palermo Cruise Port', lat: 38.1404, lng: 13.3695 },
          radius: 250,
          tag: 'cruise',
        },
        {
          time: '08:30',
          title: '하선 & 시내 진입 (도보 가능)',
          desc: '항구에서 구도심까지 도보 15분',
          tag: 'transport',
        },
        {
          time: '09:00',
          title: '발라로 시장 (Mercato del Ballarò)',
          desc: '날 것 그대로의 이탈리아. 스트리트 푸드(아란치니, 파넬레) 강추.',
          location: { name: 'Mercato del Ballarò', lat: 38.1109, lng: 13.3601 },
          radius: 200,
          tag: 'food',
        },
        {
          time: '11:00',
          title: 'ALAB (예술가 협회 샵)',
          desc: '독특한 수공예품, 시칠리아 문양 도자기.',
          location: { name: 'ALAB Palermo', lat: 38.1167, lng: 13.3613 },
          radius: 150,
          tag: 'shop',
        },
        {
          time: '12:00',
          title: '점심 식사 (이른 점심 권장)',
          desc: '시칠리아 전통 트라토리아. 16:00 마감 고려해 빠르게.',
          tag: 'food',
        },
        {
          time: '13:30',
          title: 'Vicolo d\'Oro',
          desc: '핸드메이드 주얼리 & 가죽 제품',
          location: { name: 'Vicolo d\'Oro', lat: 38.1180, lng: 13.3616 },
          radius: 100,
          tag: 'shop',
        },
        {
          time: '14:30',
          title: '카테드랄레 + 콰트로 칸티 (시간 있으면)',
          location: { name: 'Cattedrale di Palermo', lat: 38.1141, lng: 13.3563 },
          radius: 300,
          tag: 'walk',
        },
        {
          time: '15:00',
          title: '항구로 복귀 시작',
          desc: '15:30 이전 항구 도착 권장',
          tag: 'transport',
        },
        {
          time: '16:00',
          title: '⚠️ 전원 승선 마감',
          tag: 'cruise',
        },
        {
          time: '16:30',
          title: '🚢 출항 — 팔레르모 → 치비타베키아',
          tag: 'cruise',
        },
      ],
    },
    {
      date: '2026-05-15',
      weekday: '금',
      title: '🇮🇹 치비타베키아 / 로마 (Day 5)',
      subtitle: '에트루리아 또는 트라스테베레',
      city: 'Civitavecchia',
      cityCenter: { lat: 42.0939, lng: 11.7919 },
      tips: '🛳️ 08:30 입항 · 18:30 전원 승선 · 19:00 출항. 로마 왕복 2~3시간 — 빠듯. 타르퀴니아/트라스테베레 추천.',
      events: [
        {
          time: '08:30',
          title: '🛳️ 치비타베키아 입항',
          location: { name: 'Civitavecchia Port', lat: 42.0942, lng: 11.7900 },
          radius: 250,
          tag: 'cruise',
        },
        {
          time: '09:30',
          title: '선택1 · 타르퀴니아 (Tarquinia)',
          desc: '에트루리아 유적 마을. 한적하고 여유로움.',
          location: { name: 'Tarquinia', lat: 42.2547, lng: 11.7572 },
          radius: 500,
          tag: 'walk',
        },
        {
          time: '09:30',
          title: '선택2 · 로마 트라스테베레',
          desc: '로마 시내 가신다면 이 구역 추천. 빈티지샵/갤러리.',
          location: { name: 'Trastevere, Rome', lat: 41.8896, lng: 12.4675 },
          radius: 400,
          tag: 'walk',
        },
        {
          time: '12:00',
          title: 'Polvere di Tempo',
          desc: '모래시계, 나침반 등 고풍스런 소품. 신비로운 샵.',
          location: { name: 'Polvere di Tempo', lat: 41.8881, lng: 12.4691 },
          radius: 100,
          tag: 'shop',
        },
        {
          time: '13:00',
          title: '로마 점심',
          desc: '카르보나라/카초에페페 전통 트라토리아',
          tag: 'food',
        },
        {
          time: '15:30',
          title: '치비타베키아 복귀 시작',
          desc: '기차 이용 시 16:00 출발 권장 (1시간 30분 소요)',
          tag: 'transport',
        },
        {
          time: '18:30',
          title: '⚠️ 전원 승선 마감',
          tag: 'cruise',
        },
        {
          time: '19:00',
          title: '🚢 출항 — 치비타베키아 → 사보나',
          tag: 'cruise',
        },
      ],
    },
    {
      date: '2026-05-16',
      weekday: '토',
      title: '🇮🇹 사보나 (Day 6)',
      subtitle: '리구리아 해안',
      city: 'Savona',
      cityCenter: { lat: 44.3052, lng: 8.4844 },
      tips: '🛳️ 08:30 입항 · 17:00 전원 승선 · 17:30 출항. 작은 항구 도시 — 도보로 시내 모두 커버.',
      events: [
        {
          time: '08:30',
          title: '🛳️ 사보나 입항',
          location: { name: 'Savona Port', lat: 44.3052, lng: 8.4844 },
          radius: 250,
          tag: 'cruise',
        },
        {
          time: '10:00',
          title: '구시가지 산책',
          desc: '프리아마르 요새, 시스티나 예배당',
          location: { name: 'Fortezza del Priamar', lat: 44.3033, lng: 8.4869 },
          radius: 200,
          tag: 'walk',
        },
        {
          time: '12:30',
          title: '점심 식사',
          desc: '리구리아식 페스토 파스타 / 포카치아',
          tag: 'food',
        },
        {
          time: '14:00',
          title: '근교 옵션 · 제노바 당일치기',
          desc: '기차로 30분. 시간 여유 있을 때만.',
          location: { name: 'Genova Piazza Principe', lat: 44.4170, lng: 8.9239 },
          radius: 300,
          tag: 'transport',
        },
        {
          time: '16:00',
          title: '항구 복귀',
          tag: 'transport',
        },
        {
          time: '17:00',
          title: '⚠️ 전원 승선 마감',
          tag: 'cruise',
        },
        {
          time: '17:30',
          title: '🚢 출항 — 사보나 → 마르세유',
          tag: 'cruise',
        },
      ],
    },
    {
      date: '2026-05-17',
      weekday: '일',
      title: '🇫🇷 마르세유 (Day 7)',
      subtitle: '비외 포르 & 르 파니에',
      city: 'Marseille',
      cityCenter: { lat: 43.2965, lng: 5.3698 },
      tips: '🛳️ 08:30 입항 · 17:30 전원 승선 · 18:00 출항. 마지막 기항지 — 충분히 즐기되 17:00에는 항구로.',
      events: [
        {
          time: '08:30',
          title: '🛳️ 마르세유 입항',
          location: { name: 'Marseille Cruise Port', lat: 43.3503, lng: 5.3496 },
          radius: 300,
          tag: 'cruise',
        },
        {
          time: '09:00',
          title: '셔틀로 비외 포르 이동',
          desc: '항구→비외 포르 셔틀 또는 메트로',
          location: { name: 'Vieux-Port de Marseille', lat: 43.2951, lng: 5.3743 },
          radius: 200,
          tag: 'transport',
        },
        {
          time: '09:30',
          title: '비외 포르 (Vieux-Port)',
          desc: '매일 아침 열리는 수산시장 구경',
          location: { name: 'Vieux-Port de Marseille', lat: 43.2951, lng: 5.3743 },
          radius: 200,
          tag: 'walk',
        },
        {
          time: '10:30',
          title: '르 파니에 (Le Panier) 지구',
          desc: '마르세유에서 가장 오래된 동네. 골목마다 벽화와 카페.',
          location: { name: 'Le Panier', lat: 43.2989, lng: 5.3690 },
          radius: 250,
          tag: 'walk',
        },
        {
          time: '11:30',
          title: '72% Pétrole — La Grande Savonnerie',
          desc: '마르세유 천연 비누. 기념품/편집숍.',
          location: { name: 'La Grande Savonnerie', lat: 43.2963, lng: 5.3729 },
          radius: 100,
          tag: 'shop',
        },
        {
          time: '13:00',
          title: '점심 식사',
          desc: '비외 포르 근처 부야베스(bouillabaisse) 추천',
          tag: 'food',
        },
        {
          time: '15:00',
          title: '노트르담 드 라 가르드 전망 (선택)',
          desc: '마르세유 시내 한눈에. 미니버스 또는 택시.',
          location: { name: 'Notre-Dame de la Garde', lat: 43.2841, lng: 5.3711 },
          radius: 200,
          tag: 'walk',
        },
        {
          time: '16:30',
          title: '항구 복귀 시작',
          desc: '늦어도 16:30 출발',
          tag: 'transport',
        },
        {
          time: '17:30',
          title: '⚠️ 전원 승선 마감',
          tag: 'cruise',
        },
        {
          time: '18:00',
          title: '🚢 출항 — 마르세유 → 바르셀로나',
          tag: 'cruise',
        },
      ],
    },
    {
      date: '2026-05-18',
      weekday: '월',
      title: '🇪🇸 바르셀로나 하선 (Day 8)',
      subtitle: '하선 → 호텔 → 풀 데이 관광',
      city: 'Barcelona',
      cityCenter: { lat: 41.3851, lng: 2.1734 },
      tips: '🛳️ 08:00 입항 = 하선일. 짐 정리 + 호텔 짐 보관 후 풀 데이 관광.',
      events: [
        {
          time: '08:00',
          title: '🛳️ 바르셀로나 재입항 / 하선',
          location: { name: 'Barcelona Cruise Terminal', lat: 41.3536, lng: 2.1714 },
          radius: 300,
          tag: 'cruise',
        },
        {
          time: '09:00',
          title: 'H10 Universitat 호텔 짐 보관',
          location: { name: 'H10 Universitat', lat: 41.3865, lng: 2.1635 },
          radius: 150,
          tag: 'hotel',
        },
        {
          time: '10:00',
          title: '구엘 공원으로 이동 (택시)',
          location: { name: 'Park Güell', lat: 41.4145, lng: 2.1527 },
          radius: 300,
          tag: 'transport',
        },
        {
          time: '10:30',
          title: '구엘 공원 관람 (~12:30)',
          desc: '입장 시간 사전 예약 필수',
          location: { name: 'Park Güell', lat: 41.4145, lng: 2.1527 },
          radius: 300,
          tag: 'attraction',
        },
        {
          time: '13:00',
          title: '점심 (그라시아 지구 로컬 식당)',
          location: { name: 'Gràcia', lat: 41.4036, lng: 2.1554 },
          radius: 250,
          tag: 'food',
        },
        {
          time: '14:00',
          title: '베르디 거리(Carrer de Verdi) 쇼핑',
          desc: 'Casa Atlântica, LA A, noThrow Design, Verde Jade',
          location: { name: 'Carrer de Verdi', lat: 41.4040, lng: 2.1554 },
          radius: 200,
          tag: 'shop',
        },
        {
          time: '15:30',
          title: '산 파우 병원 외관 + 카페 티타임',
          location: { name: 'Hospital de Sant Pau', lat: 41.4133, lng: 2.1742 },
          radius: 200,
          tag: 'attraction',
        },
        {
          time: '16:30',
          title: '사그라다 파밀리아로 도보 이동',
          location: { name: 'Sagrada Família', lat: 41.4036, lng: 2.1744 },
          radius: 250,
          tag: 'walk',
        },
        {
          time: '17:45',
          title: '사그라다 파밀리아 + 타워 (~18:30)',
          desc: '타워 입장권 별도 예약 필수',
          location: { name: 'Sagrada Família', lat: 41.4036, lng: 2.1744 },
          radius: 200,
          tag: 'attraction',
        },
        {
          time: '19:30',
          title: '사그라다 야경 + 저녁 (Ciutat Comtal)',
          location: { name: 'Ciutat Comtal', lat: 41.3915, lng: 2.1665 },
          radius: 150,
          tag: 'food',
        },
        {
          time: '21:30',
          title: 'H10 Universitat 호텔 체크인',
          location: { name: 'H10 Universitat', lat: 41.3865, lng: 2.1635 },
          radius: 150,
          tag: 'hotel',
        },
      ],
    },
    {
      date: '2026-05-19',
      weekday: '화',
      title: '🇪🇸 바르셀로나 마지막 날 → 귀국',
      subtitle: '까사 바트요 → 쇼핑 → 공항',
      city: 'Barcelona',
      cityCenter: { lat: 41.3851, lng: 2.1734 },
      events: [
        {
          time: '09:30',
          title: '체크아웃 (프론트 짐 보관)',
          location: { name: 'H10 Universitat', lat: 41.3865, lng: 2.1635 },
          radius: 150,
          tag: 'hotel',
        },
        {
          time: '10:00',
          title: '까사 바트요 외관 관람 & 사진',
          location: { name: 'Casa Batlló', lat: 41.3917, lng: 2.1649 },
          radius: 100,
          tag: 'attraction',
        },
        {
          time: '10:30',
          title: '심볼릭 (Simbòlic) 스토어',
          desc: '까사 바트요 1층',
          location: { name: 'Casa Batlló Store', lat: 41.3917, lng: 2.1649 },
          radius: 100,
          tag: 'shop',
        },
        {
          time: '11:30',
          title: 'ZARA 쇼핑 (그라시아 거리)',
          location: { name: 'ZARA Passeig de Gràcia', lat: 41.3924, lng: 2.1647 },
          radius: 100,
          tag: 'shop',
        },
        {
          time: '13:00',
          title: '점심 (쇼핑 거리 인근)',
          tag: 'food',
        },
        {
          time: '14:30',
          title: '엘 코르테 잉글레스 + 그라시아 쇼핑',
          desc: '양가 부모님 선물',
          location: { name: 'El Corte Inglés Plaça Catalunya', lat: 41.3870, lng: 2.1701 },
          radius: 150,
          tag: 'shop',
        },
        {
          time: '17:00',
          title: '호텔 복귀, 짐 찾기 & 캐리어 정리',
          location: { name: 'H10 Universitat', lat: 41.3865, lng: 2.1635 },
          radius: 150,
          tag: 'hotel',
        },
        {
          time: '17:30',
          title: '까탈루냐 광장 → 공항버스(Aerobús)',
          location: { name: 'Plaça de Catalunya', lat: 41.3870, lng: 2.1701 },
          radius: 100,
          tag: 'transport',
        },
        {
          time: '18:15',
          title: '공항 도착, 택스 리펀 & 출국 수속',
          location: { name: 'Barcelona–El Prat Airport (BCN)', lat: 41.2974, lng: 2.0833 },
          radius: 500,
          tag: 'transport',
        },
        {
          time: '20:50',
          title: '✈️ 비행기 탑승 & 귀국 출발',
          tag: 'flight',
        },
      ],
    },
  ],
};

// Default packing checklist (shared/syncable)
const DEFAULT_CHECKLIST = [
  {
    category: '필수 서류',
    items: [
      '여권 (유효기간 6개월 이상)',
      '여권 사본 / 사진 (분실 대비)',
      '항공권 / e-Ticket',
      '크루즈 승선권 (Boarding Pass)',
      '호텔 예약 확인서 (SM Teatre, H10 Universitat)',
      '여행자 보험 증서',
      '튀니지 비자 면제 확인 (한국 여권 90일 무비자 OK)',
      '국제운전면허증 (필요 시)',
      '신용카드 2장 이상 (서로 다른 카드사)',
      '체크카드 (해외 ATM용)',
      '소액 유로 현금 (€200~300)',
      '튀니지 디나르 (선상 ATM 또는 항구)',
    ],
  },
  {
    category: '전자기기',
    items: [
      '핸드폰 + 충전기 (남편)',
      '핸드폰 + 충전기 (와이프)',
      '보조 배터리 (10000mAh+)',
      '유럽용 220V 멀티 어댑터 (C/F 타입)',
      '튀니지용 어댑터 (C/E 타입 — 유럽과 호환)',
      '카메라 + 메모리카드 + 충전기',
      '셀카봉 / 미니삼각대',
      '유심 또는 e심 (유럽+북아프리카)',
      '이어폰',
      '노트북 (선택)',
    ],
  },
  {
    category: '의류 (5월 지중해 평균 18~24도, 튀니지는 더 더움)',
    items: [
      '얇은 가디건 / 자켓 (밤에 쌀쌀)',
      '반팔 셔츠 5~6벌',
      '긴팔 셔츠 2~3벌',
      '반바지 / 면바지',
      '편한 운동화 (하루 2만보 가정)',
      '샌들',
      '구두 / 드레스 슈즈 (갈라 디너용)',
      '드레스 / 자켓 (갈라 디너 드레스 코드)',
      '수영복',
      '속옷 / 양말 (10일치)',
      '잠옷',
      '모자 (햇빛 강함, 튀니지 필수)',
      '선글라스',
      '비올 때용 우산 / 우비',
      '여성 어깨 가리개 (튀니지 종교 시설 입장 시)',
    ],
  },
  {
    category: '세면도구 / 의약품',
    items: [
      '칫솔 / 치약',
      '스킨케어 (소분)',
      '선크림 (SPF50)',
      '샴푸 / 린스 (호텔 비치 안 될 수 있음)',
      '면도기',
      '여성용품',
      '두통/감기/소화제',
      '지사제 / 멀미약 (튀니지 음식 적응)',
      '밴드 / 연고',
      '개인 처방약 (영문 처방전 동봉)',
      '비타민',
      '모기 기피제 (튀니지/이탈리아 남부)',
    ],
  },
  {
    category: '여행 편의용품',
    items: [
      '캐리어 (위탁수하물)',
      '기내용 캐리어',
      '에코백 / 보조가방',
      '여행용 자물쇠',
      '지퍼백 (액체 분리용)',
      '압축팩',
      '세탁세제 시트 (선상 세탁용)',
      '물티슈 / 휴지',
      '가이드북 / 메모지 / 펜',
      '눈가리개 / 목베개 (장거리 비행)',
    ],
  },
  {
    category: '기념품 / 쇼핑 메모',
    items: [
      '양가 부모님 선물 리스트 정리',
      '엘 코르테 잉글레스 면세 리펀 영수증 모으기',
      'White & Blue Cages 수공예 (튀니지 시디 부 사이드)',
      'Rock the Kasbah 세라믹/카페트 (튀니지)',
      'ALAB 시칠리아 도자기 (팔레르모)',
      'Polvere di Tempo 모래시계 (로마)',
      'La Grande Savonnerie 비누 (마르세유)',
      '심볼릭 (Simbòlic) 굿즈 (까사 바트요)',
    ],
  },
];

// Important warnings/notes (always visible on Tips tab)
const TRAVEL_TIPS = [
  {
    category: '크루즈 재승선 (가장 중요)',
    icon: '⚠️',
    items: [
      '항구별 재승선 시간을 절대 늦지 말 것. 늦으면 다음 항구에서 자비로 합류해야 함.',
      '5/13 튀니지: 17:30 마감 / 18:00 출항',
      '5/14 팔레르모: 16:00 마감 / 16:30 출항 (가장 짧음 — 일찍 점심)',
      '5/15 치비타베키아: 18:30 마감 / 19:00 출항',
      '5/16 사보나: 17:00 마감 / 17:30 출항',
      '5/17 마르세유: 17:30 마감 / 18:00 출항 (마지막 기항지)',
      '하선 시 선상 시간(Ship Time) 기준임을 확인 — 현지 시간과 다를 수 있음.',
      '여권은 선실 금고에, 외출 시에는 승선 카드(Cruise Card)만 휴대.',
    ],
  },
  {
    category: '튀니지 특이사항',
    icon: '🇹🇳',
    items: [
      '한국 여권 = 무비자 90일 체류. 별도 비자 X.',
      '통화: 튀니지 디나르(TND). 1 EUR ≈ 3.5 TND. 현금 위주 사회.',
      '시디 부 사이드까지 항구에서 차로 20분 — 택시 가격 협상 필수 (왕복 €30~40 적정).',
      '여성: 보수적인 옷차림 권장 (어깨/무릎 노출 최소화).',
      '음식 주의: 길거리 음식보다 호텔/유명 식당 권장. 생수 필수.',
      '소매치기 주의: 사진 찍는 척 접근 후 가방 노림. 가방 앞으로.',
      '사진 촬영: 사람 찍기 전 반드시 동의 — 특히 여성/노인.',
    ],
  },
  {
    category: '소매치기 / 안전',
    icon: '🛡️',
    items: [
      '바르셀로나 람블라스, 메트로, 사그라다 파밀리아 주변은 소매치기 핫스팟.',
      '가방은 앞으로 메기. 스마트폰은 식당 테이블 위에 두지 말기.',
      '로마 트라스테베레, 팔레르모 시장도 소매치기 주의.',
      '튀니지 시디 부 사이드 시장도 주의.',
      '여권 사진을 클라우드(구글 포토 등)에 백업.',
    ],
  },
  {
    category: '식당 / 매너',
    icon: '🍽️',
    items: [
      '이탈리아: 점심은 12:30~14:30, 저녁은 19:30 이후. 그 외 시간은 닫혀 있을 수 있음.',
      '스페인: 저녁 식당은 20:30 이후 정상 영업.',
      '튀니지: 라마단 기간 외엔 정상 영업. 음주 가능 식당 한정.',
      '팁은 보통 5~10% (이탈리아는 코페르토 — 자릿세 있음).',
      '물은 \'Acqua naturale (still)\' / \'frizzante (sparkling)\' 구분.',
    ],
  },
  {
    category: '쇼핑 / 면세',
    icon: '🛍️',
    items: [
      'EU 면세는 €175 이상 한 매장에서 구매 시 가능.',
      '튀니지는 EU 외 — 별도 세금 환급 절차 (Tax Refund 카운터).',
      '엘 코르테 잉글레스에서 면세 신청서 작성 후 공항 세관에서 도장.',
      '바르셀로나 공항(BCN) 세관은 줄이 길 수 있어 3시간 이전 도착 권장.',
    ],
  },
  {
    category: '결제 / 환전',
    icon: '💳',
    items: [
      '대부분 카드 결제 가능 (튀니지 제외). 트래블월렛/트래블로그 추천.',
      'DCC(원화 결제) 묻으면 반드시 \'EUR\' 선택.',
      '튀니지: 카드 안 받는 곳 많음. 소액 디나르 현금 필수.',
      '시장/소형 식당은 현금만 받는 곳도 있음.',
    ],
  },
  {
    category: '커뮤니케이션',
    icon: '📱',
    items: [
      'EU 다국가 유심 또는 e심 (Holafly, Airalo 등) — 튀니지 포함된 플랜 확인 필요.',
      '크루즈 선내 와이파이는 별도 패키지 필요. 보통 비싸서 항구에서만 데이터 쓰기.',
      '구글맵 오프라인 지도 — 도시별 미리 다운로드.',
      '튀니지: 데이터 안 잡힐 수 있음. 호텔/카페 와이파이 활용.',
    ],
  },
];
